server:
  port: 8888


spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jake-huen/spring-cloud-config # file:///Users/kimtaeheon/Desktop/git-local-repo
          # private repository?? ?? ?? ??
          #username: Jake-huen
          #password: